#!/bin/sh
#
# @name Cloudship SITL
#

. ${R}etc/init.d/rc.airship_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=cloudship}

param set-default CA_AIRFRAME 9

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_MAGSIM 1
param set-default SENS_EN_ARSPDSIM 1

param set-default CA_ROTOR_COUNT 3

param set-default CA_ROTOR0_AX 1
param set-default CA_ROTOR0_AZ 0
param set-default CA_ROTOR0_KM 0
param set-default CA_ROTOR0_PY 2

param set-default CA_ROTOR1_AX 1
param set-default CA_ROTOR1_AZ 0
param set-default CA_ROTOR1_KM 0
param set-default CA_ROTOR1_PY -2

param set-default CA_ROTOR2_AY -1
param set-default CA_ROTOR2_AZ 0
param set-default CA_ROTOR2_KM 0
param set-default CA_ROTOR2_PX -10

param set-default CA_SV_CS_COUNT 1
param set-default CA_SV_CS0_TRQ_P 1

param set-default CA_R_REV 7

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103

param set-default SIM_GZ_EC_MIN1 10
param set-default SIM_GZ_EC_MIN2 10
param set-default SIM_GZ_EC_MIN3 10

param set-default SIM_GZ_EC_MAX1 1600
param set-default SIM_GZ_EC_MAX2 1600
param set-default SIM_GZ_EC_MAX3 1600

param set-default SIM_GZ_SV_FUNC1 201

