#!/bin/sh
#
# @name Custom Airship (gz)
# @type Airship
# @class Airship
#
# @maintainer Your Name <you@example.com>
#
# @output Motor1 starboard thruster
# @output Motor2 port thruster
# @output Motor3 tail thruster
# @output Servo1 thrust tilt
#
# Notes:
# - For PX4 SITL with Gazebo Sim (gz) airship model "custom_airship".
# - Sensors come from gz-bridge topics; do NOT enable *_SIM sensors here.
# - Geometry & actuator output mapping should be finalized in QGC Actuators.

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=airship_world}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=custom_airship}

param set-default SIM_GZ_EN 1
